import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {sqliteAdapter,migrate} from '../scripts/sqlite-adapter.mjs';
import {handle} from '../server/worker.mjs';
import data from '../dist/data.js';

function setup(t,filename=':memory:'){
 const db=sqliteAdapter(filename);migrate(db,path.resolve('drizzle'));t.after(()=>db.close());const env={DB:db,OWNER_EMAIL:'owner@test.local',ASSETS:{fetch:()=>new Response('static')}};
 async function call(route,{who='author',method='GET',value,headers={},transport}={}){
  const h={'content-type':'application/json','x-prg-request':'1',origin:'https://lab.test',...headers};if(who){h['oai-authenticated-user-id']=who;h['oai-authenticated-user-email']=who+'@test.local';}
  const response=await handle(new Request('https://lab.test/api'+route,{method,headers:h,...(value?{body:JSON.stringify(value)}:{})}),env,transport);
  const raw=await response.text();let result;try{result=JSON.parse(raw);}catch{result=raw;}return {status:response.status,result};
 }
 async function create(who='author',source=data.scenarios.brief[0],type='brief'){return (await call('/drafts',{who,method:'POST',value:{type,source,syntheticOnly:true}})).result.draft;}
 return {db,env,call,create};
}
test('API requires identity and rejects cross-site writes',async t=>{const {call}=setup(t);assert.equal((await call('/me',{who:null})).status,401);assert.equal((await call('/drafts',{method:'POST',value:{},headers:{origin:'https://evil.test'}})).status,403);});
test('members cannot read, edit or approve another person’s draft',async t=>{const {call,create}=setup(t);const d=await create();assert.equal((await call('/drafts/'+d.id,{who:'other'})).status,404);assert.equal((await call('/drafts/'+d.id,{who:'other',method:'PATCH',value:{version:1}})).status,404);assert.equal((await call('/drafts/'+d.id+'/review',{method:'POST',value:{version:1,decision:'approve',confirmed:true}})).status,403);});
test('review lifecycle records actor/version and editing invalidates approval',async t=>{const {call,create}=setup(t);const d=await create();assert.equal((await call('/drafts/'+d.id+'/export')).status,403);let r=await call('/drafts/'+d.id+'/submit',{method:'POST',value:{version:1}});assert.equal(r.result.draft.status,'submitted');r=await call('/drafts/'+d.id+'/review',{who:'owner',method:'POST',value:{version:2,decision:'approve',confirmed:true,note:'Facts checked.'}});assert.equal(r.result.draft.status,'approved');assert.equal((await call('/drafts/'+d.id+'/export')).status,200);r=await call('/drafts/'+d.id,{method:'PATCH',value:{version:3,title:'Updated title',source:data.scenarios.brief[0],output:'A revised draft.'}});assert.equal(r.result.draft.status,'draft');assert.equal((await call('/drafts/'+d.id+'/export')).status,403);const full=(await call('/drafts/'+d.id)).result;assert.equal(full.events.length,4);assert.equal(full.events[2].actor_id,'owner');assert.equal(full.events[2].kind,'approve');assert.equal(JSON.parse(full.events[2].snapshot).status,'approved');});
test('stale updates and approvals cannot overwrite a newer version',async t=>{const {call,create}=setup(t);const d=await create();await call('/drafts/'+d.id+'/submit',{method:'POST',value:{version:1}});const r=await call('/drafts/'+d.id,{method:'PATCH',value:{version:1,source:data.scenarios.brief[0],output:'Stale write'}});assert.equal(r.status,409);assert.equal((await call('/drafts/'+d.id)).result.events.length,2);});
test('missing salary or contact permission cannot be submitted by bypassing the UI',async t=>{const {call,create}=setup(t);for(const [source,type] of [[data.scenarios.brief[1],'brief'],[data.scenarios.care[1],'care']]){const d=await create('author',source,type);assert.equal((await call('/drafts/'+d.id+'/submit',{method:'POST',value:{version:1}})).status,422);}});
test('owner can grant reviewer, while a member cannot elevate their role',async t=>{const {call,create}=setup(t);await call('/me',{who:'riley'});assert.equal((await call('/users',{method:'PATCH',value:{id:'author',role:'reviewer'}})).status,403);assert.equal((await call('/users',{who:'owner',method:'PATCH',value:{id:'riley',role:'reviewer'}})).status,200);const d=await create();assert.equal((await call('/drafts/'+d.id,{who:'riley'})).status,200);assert.equal((await call('/users',{who:'owner',method:'PATCH',value:{id:'riley',role:'admin'}})).status,400);});
test('business cases are recalculated server-side and remain private',async t=>{const {call}=setup(t);const r=await call('/cases',{method:'POST',value:{name:'Baseline',inputs:{users:10,tasks:8,hourly:65,review:3,weeks:46},paths:data.paths,results:[{net1:9999999}]}});assert.equal(r.result.results[0].net1,15530);assert.equal((await call('/cases',{who:'other'})).result.cases.length,0);assert.equal((await call('/cases')).result.cases.length,1);});
test('trial recording validates included review time and persists unsuccessful cases',async t=>{const {call}=setup(t);const b={workflow:'brief',baseline:10,assisted:6,review:7,corrections:1,criticalErrors:1,accepted:false};assert.equal((await call('/measurements',{method:'POST',value:b})).status,400);b.review=2;assert.equal((await call('/measurements',{method:'POST',value:b})).status,201);assert.equal((await call('/measurements')).result.measurements[0].accepted,0);assert.equal((await call('/measurements',{who:'other'})).result.measurements.length,0);});
test('priority snapshots validate dimensions and calculate their own scores',async t=>{const {call}=setup(t);const r=await call('/priorities',{method:'POST',value:{name:'Review',scores:data.opportunities}});assert.equal(r.status,201);assert.equal(r.result.scores.length,16);assert.equal((await call('/priorities',{who:'other'})).result.snapshots.length,0);});
test('missing AI configuration never returns a simulated model answer',async t=>{const {call}=setup(t);const r=await call('/assistant',{method:'POST',value:{message:'Hello',syntheticOnly:true}});assert.equal(r.status,503);assert.ok(r.result.error.includes('No message was sent'));});
test('exhausted API credits are distinct from transient rate limiting and save no fake answer',async t=>{const {call,env}=setup(t);env.OPENAI_API_KEY='test';env.OPENAI_MODEL='test';const r=await call('/assistant',{method:'POST',value:{message:'Explain review time.',syntheticOnly:true},transport:async()=>Response.json({error:{type:'insufficient_quota',code:'credit_balance_exhausted'}},{status:429})});assert.equal(r.status,503);assert.match(r.result.error,/API credits/);assert.equal((await call('/assistant/messages')).result.messages.length,0);});
test('AI uses a server credential, authorised context, bounded output and private history',async t=>{const {call,env,create}=setup(t);env.OPENAI_API_KEY='test-secret-not-real';env.OPENAI_MODEL='test-model';const d=await create();let sent;
 const transport=async(url,options)=>{sent={url,options,body:JSON.parse(options.body)};return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Check the approved role brief before release. [R1]'}]}]});};
 const r=await call('/assistant',{method:'POST',value:{message:'Review this example.',draftId:d.id,syntheticOnly:true},transport});assert.equal(r.status,200);assert.equal(sent.url,'https://api.openai.com/v1/responses');assert.equal(sent.body.store,false);assert.equal(sent.body.max_output_tokens,1400);assert.ok(sent.body.instructions.includes(d.id));assert.equal(sent.options.headers.Authorization,'Bearer test-secret-not-real');assert.ok(!JSON.stringify(r.result).includes('test-secret'));assert.equal((await call('/assistant/messages')).result.messages.length,2);assert.equal((await call('/assistant/messages',{who:'other'})).result.messages.length,0);assert.equal((await call('/assistant',{who:'other',method:'POST',value:{message:'Read another draft',draftId:d.id,syntheticOnly:true},transport})).status,404);
});
test('AI rate limits are enforced before an external call',async t=>{const {call,env,db}=setup(t);env.OPENAI_API_KEY='test';env.OPENAI_MODEL='test';await call('/me');const day=new Date().toISOString().slice(0,10);await db.prepare('INSERT INTO assistant_limits(key,count) VALUES (?,?)').bind('author:'+day,20).run();let invoked=false;const r=await call('/assistant',{method:'POST',value:{message:'Hello',syntheticOnly:true},transport:async()=>{invoked=true;}});assert.equal(r.status,429);assert.equal(invoked,false);});
test('SQL records survive closing and reopening the database',async t=>{const folder=mkdtempSync(path.join(os.tmpdir(),'prg-test-')),file=path.join(folder,'test.sqlite');const db=sqliteAdapter(file);migrate(db,path.resolve('drizzle'));await db.prepare('INSERT INTO users(id,email,name,role,created_at) VALUES (?,?,?,?,?)').bind('persist','test@local','Test','member',new Date().toISOString()).run();db.close();const reopened=sqliteAdapter(file);assert.equal((await reopened.prepare('SELECT name FROM users WHERE id=?').bind('persist').first()).name,'Test');reopened.close();assert.ok(path.resolve(folder).startsWith(path.resolve(os.tmpdir())+path.sep+'prg-test-'));rmSync(folder,{recursive:true});});
