import {test} from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import {sqliteAdapter,migrate} from '../scripts/sqlite-adapter.mjs';
import {handle} from '../server/worker.mjs';
import {demoRecords} from '../dist/enrichment-data.mjs';
import {journeys,platformById,validateWorkspaceUrl} from '../dist/platforms.mjs';
function setup(t){const DB=sqliteAdapter();migrate(DB,path.resolve('drizzle'));t.after(()=>DB.close());const env={DB,OWNER_EMAIL:'owner@test.local',ASSETS:{fetch:()=>new Response('asset')}};
 const call=async(route,{who='owner',method='GET',value,origin='https://test.local'}={})=>{const headers={'content-type':'application/json','x-prg-request':'1',origin};if(who){headers['oai-authenticated-user-id']=who;headers['oai-authenticated-user-email']=who+'@test.local';}const r=await handle(new Request('https://test.local/api'+route,{method,headers,...(value?{body:JSON.stringify(value)}:{})}),env);return {status:r.status,...await r.json()};};
 const create=async(value={})=>{const d=await call('/workbench/items',{method:'POST',value:{title:'Demo case',kind:'permanent',syntheticOnly:true,...value}});assert.equal(d.status,201,JSON.stringify(d));return d.item;};return {call,create,DB};}
test('workbench requires authentication, same-origin and synthetic acknowledgement',async t=>{const {call}=setup(t);assert.equal((await call('/workbench',{who:null})).status,401);assert.equal((await call('/workbench/items',{method:'POST',value:{},origin:'https://bad.test'})).status,403);assert.equal((await call('/workbench/items',{method:'POST',value:{kind:'client',title:'Test'}})).status,400);});
test('work items persist, stay private even from another admin, and validate input',async t=>{const {call,create}=setup(t);const w=await create({due:'2026-10-03',assignee:'Demo consultant'});assert.equal((await call('/workbench')).items[0].payload.assignee,'Demo consultant');assert.equal((await call('/workbench',{who:'other'})).items.length,0);assert.equal((await call('/workbench/items/'+w.id,{who:'other'})).status,404);assert.equal((await call('/workbench/items',{method:'POST',value:{syntheticOnly:true,title:'Bad',kind:'client',due:'2026-02-30'}})).status,400);});
test('stage progress requires all checkpoints and evidence; duplicate versions add no extra event',async t=>{const {call,create}=setup(t);const w=await create();const progress=value=>call(`/workbench/items/${w.id}/progress`,{method:'POST',value:{version:1,...value}});assert.equal((await progress({checks:[true,false],advance:true,evidence:'Demo'})).status,422);assert.equal((await progress({checks:[true,true],advance:true})).status,422);assert.equal((await progress({checks:[true],advance:true,evidence:'Demo'})).status,400);const results=await Promise.all([1,2].map(()=>progress({checks:[true,true],advance:true,evidence:'Demo brief approved'})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const d=await call('/workbench/items/'+w.id);assert.equal(d.item.stage,1);assert.equal(d.events.length,2);});
test('partial checkpoints persist without advancing, notes and packets are auditable',async t=>{const {call,create}=setup(t);const w=await create({kind:'contract'});let d=await call(`/workbench/items/${w.id}/progress`,{method:'POST',value:{version:1,checks:[true,false,false],advance:false,evidence:'Draft W/O'}});assert.equal(d.item.stage,0);assert.deepEqual(d.item.payload.checks[0],[true,false,false]);d=await call(`/workbench/items/${w.id}/note`,{method:'POST',value:{version:2,note:'Fictional call outcome',platform:'corecruit'}});assert.equal(d.status,200);d=await call(`/workbench/items/${w.id}/packet`,{method:'POST',value:{version:3}});assert.equal(d.packet.status,'In progress');assert.equal(d.packet.history.length,3);assert.match(d.packet.disclaimer,/No platform sync/);assert.equal(d.item.version,4);assert.equal((await call('/workbench/items/'+w.id)).events.at(-1).kind,'packet_exported');});
test('linked enrichment must match owner and workflow; relinking resets downstream checkpoints',async t=>{const {call,create}=setup(t);const seeded=await call('/enrichment/records',{method:'POST',value:{syntheticOnly:true,records:demoRecords()}});const r=seeded.records.find(r=>r.workflow==='permanent'&&r.kind==='candidate');const w=await create({recordId:r.id});assert.equal((await call('/workbench/items',{method:'POST',value:{title:'Mismatch',kind:'client',recordId:r.id,syntheticOnly:true}})).status,400);assert.equal((await call('/workbench/items',{who:'other',method:'POST',value:{title:'Wrong owner',kind:'permanent',recordId:r.id,syntheticOnly:true}})).status,404);let version=1;for(let i=0;i<2;i++){const d=await call(`/workbench/items/${w.id}/progress`,{method:'POST',value:{version,checks:journeys.permanent.steps[i].checks.map(()=>true),advance:true,evidence:'Synthetic evidence'}});assert.equal(d.status,200);version=d.item.version;}const d=await call(`/workbench/items/${w.id}`,{method:'PATCH',value:{version,title:'Relinked',recordId:'',assignee:'Me'}});assert.equal(d.item.stage,1);assert.equal(d.item.payload.checks[1],undefined);assert.ok(d.item.payload.checks[0]);});
test('platform setup is version guarded, private and can never self-assert a live connection',async t=>{const {call}=setup(t);let d=await call('/workbench/platforms/jobadder',{method:'PUT',value:{version:0,workspaceUrl:'https://app.jobadder.com/',pinned:true,connected:true,readiness:{access:true}}});assert.equal(d.status,200);assert.equal(d.setting.payload.connected,false);assert.equal((await call('/workbench')).liveConnections,0);assert.equal((await call('/workbench',{who:'other'})).settings.length,0);assert.equal((await call('/workbench/platforms/jobadder',{method:'PUT',value:{version:0}})).status,409);assert.equal((await call('/workbench/platforms/jobadder',{method:'PUT',value:{version:1,workspaceUrl:'https://evil.test'}})).status,400);});
test('platform shortcuts reject credential URLs and deceptive hosts',()=>{const p=platformById('jobadder');for(const s of ['javascript:alert(1)','http://app.jobadder.com','https://jobadder.com.evil.test','https://token@app.jobadder.com','https://app.jobadder.com/?access_token=secret','https://app.jobadder.com/#secret'])assert.throws(()=>validateWorkspaceUrl(s,p));assert.equal(validateWorkspaceUrl('https://app.jobadder.com/',p),'https://app.jobadder.com/');});
test('all workflow stages can complete in order with a clear completed handoff',async t=>{const {call,create}=setup(t);const w=await create({kind:'client'});let version=1;for(const step of journeys.client.steps){const d=await call(`/workbench/items/${w.id}/progress`,{method:'POST',value:{version,checks:step.checks.map(()=>true),advance:true,evidence:'Synthetic checkpoint outcome'}});assert.equal(d.status,200);version=d.item.version;}const d=await call(`/workbench/items/${w.id}/packet`,{method:'POST',value:{version}});assert.equal(d.packet.status,'Checklist complete');assert.equal(d.packet.completedStages,d.packet.totalStages);assert.equal((await call(`/workbench/items/${w.id}/progress`,{method:'POST',value:{version:d.item.version}})).status,409);});
